print "Welcome to the survey!"
name1 = raw_input("What is your name? ")
name2 = raw_input("What is your name? ")
color1 = raw_input("What is %s's favorite color? "%(name1))
color2 = raw_input("What is %s's favorite color? "%(name2))
hobby1 = raw_input("What is %s's favorite hobby? "%(name1))
hobby2 = raw_input("What is %s's favorite hobby? "%(name2))
movie1 = raw_input("What is %s's favorite movie? "%(name1))
movie2 = raw_input("What is %s's favorite movie? "%(name2))
food1 = raw_input("What is %s's favorite food? "%(name1))
food2 = raw_input("What is %s's favorite food? "%(name2))
dog1 = raw_input("What is the name of %s's dog? "%(name1))
dog2 = raw_input("What is the name of %s's dog? "%(name2))
print "%s's favorite color is %s" %(name1, color1)
print "%s's favorite color is %s" %(name2, color2)
print "%s's favorite hobby is %s" %(name1, hobby1)
print "%s's favorite hobby is %s" %(name2, hobby2)
print "%s's favorite movie is %s" %(name1, movie1)
print "%s's favorite movie is %s" %(name2, movie2)
print "%s's favorite food is %s" %(name1, food1)
print "%s's favorite food is %s" %(name2, food2)
print "%s's dog is %s" %(name1,dog1)
print "%s's dog is %s" %(name2,dog2)